### ISSUE TITLE
Document how different entities are to be referenced

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#16]
Most are to be referred in the `/../.../...` form following the document hierarchy. Some components where a size is provided are to be referenced using the `[..]` index notation. It'll be good to document this somewhere so it is clear to users.

**Comment by sanjayankur31** [comment]
I'm not sure if this is consistent. When using NEURON, one *must* use the `/../` form, it does not accept the `[ ]/' form at all. 

This works:
``` python
    simulation.add_column_to_output_file("output0",
                                         column_id="pop0_0_v_Seg1_dend_1",
                                         quantity="pop0/0/olm/7/v")
```

but this does not:

``` python
    simulation.add_column_to_output_file("output0",
                                         column_id="pop0_0_v_Seg1_dend_1",
                                         quantity="pop0[0]/olm/7/v")
```

It results in a NEURON writer error, so either there's a bug in the writer class, or there's another reason why this doesn't work:


```
Exception in thread "main" java.lang.NullPointerException
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getExposure(LEMSQuantityPathNeuron.java:91)
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getExposure(LEMSQuantityPathNeuron.java:117)
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getDimension(LEMSQuantityPathNeuron.java:151)
        at org.neuroml.export.neuron.NeuronWriter.getMainScript(NeuronWriter.java:1400)
        at org.neuroml.export.neuron.NeuronWriter.generateMainScriptAndMods(NeuronWriter.java:277)
        at org.neuroml.export.neuron.NeuronWriter.generateAndRun(NeuronWriter.java:155)
        at org.neuroml.JNeuroML.main(JNeuroML.java:517)
```

I'm also unclear why one has to mention the name of the cell component (`olm`) in this case here.

**Comment by sanjayankur31** [comment]
Using `[0]` works fine in the izhikevich example, even with NEURON, so it looks like it works for cells that do not have multiple compartments. Again, not sure if this is a LEMS thing or an export bug.

**Comment by sanjayankur31** [comment]
@pgleeson, using indexing without the cell name does not work. So here's what I have so far. Noting this here so I can remove it from the example in the docs.

``` python
    simulation.add_column_to_output_file("output0",
                                         column_id="pop0_0_v_Seg1_dend_1",
                                         quantity="pop0/0/olm/7/v")
    # TODO: why does the name of the cell component have to be included? This
    # does not work, for example.
    """
    simulation.add_column_to_output_file("output0",
                                         column_id="pop0_0_v_Seg1_dend_1",
                                         quantity="pop0/0/7/v")
    """
    # TODO: why does indexing not work in this population?
    """
    simulation.add_column_to_output_file("output0",
                                         column_id="pop0_0_v_Seg1_dend_1",
                                         quantity="pop0[0]/olm/7/v")


    """
    # TODO: this does not work
    """
    simulation.add_column_to_output_file("output0",
                                         column_id="pop0_0_v_Seg1_dend_1",
                                         quantity="pop0[0]/7/v")
    """
```

All the cases that do not work give errors of this form:

```
Exception in thread "main" java.lang.NullPointerException
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getExposure(LEMSQuantityPathNeuron.java:91)
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getExposure(LEMSQuantityPathNeuron.java:117)
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getDimension(LEMSQuantityPathNeuron.java:151)
        at org.neuroml.export.neuron.NeuronWriter.getMainScript(NeuronWriter.java:1400)
        at org.neuroml.export.neuron.NeuronWriter.generateMainScriptAndMods(NeuronWriter.java:277)
        at org.neuroml.export.neuron.NeuronWriter.generateAndRun(NeuronWriter.java:155)
        at org.neuroml.JNeuroML.main(JNeuroML.java:517)
```

**Comment by sanjayankur31** [comment]
Duplicate of https://github.com/NeuroML/Documentation/issues/15
